
CREATE TABLE USERS(
    ID INT PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) NOT NULL
    BIRTH_DATE CHAR(10) NOT NULL,
    GENDER ENUM('M', 'F') NOT NULL
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
);

CREATE TABLE PHOTOS(
    ID INT PRIMARY KEY NOT NULL,
    CATRGORY_ID INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
);


CREATE TABLE CATEGORY {
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
}

CREATE TABLE PHOTO_GROUPS {
    ID INT PRIMARY KEY NOT NULL,
    REPRESENT_PHOTO_ID INT PRIMARY KEY NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
}

CREATE TABLE USERS_PHOTOS_COMMENT {
    ID INT PRIMARY KEY NOT NULL,
    USER_ID INT PRIMARY KEY NOT NULL,
    PHOTO_ID INT PRIMARY KEY NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
}

CREATE TABLE USERS_PHOTO_GROUPS_COMMENT {
    ID INT PRIMARY KEY NOT NULL,
    USER_ID INT PRIMARY KEY NOT NULL,
    PHOTO_GROUP_ID INT PRIMARY KEY NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT DATE DEFAULT sysdate,
    UPDATED_AT DATE DEFAULT sysdate,
}
